In [1]:
import numpy as np
import pandas as pd


In [2]:
dataset = pd.read_csv('./Data.csv')

In [3]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
dataset.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [5]:
X= dataset.iloc[: , :-1].values
y  = dataset.iloc[ : , -1:].values

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train ,y_test = train_test_split(X, y, test_size=0.2 , random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
y_train = sc.fit_transform(y_train)

In [10]:
y_train

array([[ 1.15069786],
       [ 0.79540777],
       [-1.30936356],
       ...,
       [ 0.27595724],
       [ 0.49346982],
       [-1.53508417]])

In [11]:
from sklearn.svm import SVR
regressor = SVR(kernel= 'rbf')
regressor.fit(x_train , y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [12]:
y_pred = regressor.predict(x_test)

In [13]:
y_pred

array([-1.18727339,  0.21311322,  0.39445405, ...,  0.9556216 ,
       -0.87278266,  0.38779571])

In [14]:
y_pred = sc.inverse_transform(y_pred)

In [15]:
y_pred

array([434.05242921, 457.93810186, 461.03113894, ..., 470.60268461,
       439.41653548, 460.91757115])

In [16]:
from sklearn.metrics import r2_score
print(r2_score(y_test , y_pred))

0.9480784049986258
